name: ${project.artifactId}
version: ${project.version}
main: net.infinicraft.parties.bungee.PartiesProxy
author: XenoJava
website: www.xenojava.com
description:
         A project developed for and only Infinicraft.net This project
         was all made possible by the plugin developer and requester!
